import { mkdirSync, readFileSync, writeFileSync, renameSync } from 'node:fs'
import { basename, join } from 'node:path'
import { randomUUID } from 'node:crypto'

/** How a terminal reaches the board: the Electron binary run as Node plus
 *  the bundled board CLI script. */
export interface BoardRuntime { runtime: string; cli: string }

const shellQuote = (value: string) => `'${value.replace(/'/g, `'\\''`)}'`

/** Write the `agent-hub-board` command into `<dir>/bin` and return that
 *  directory for PATH. Rewritten only when the runtime or CLI path changes. */
export function writeBoardShim(directory: string, board: BoardRuntime): string {
  const bin = join(directory, 'bin')
  const path = join(bin, 'agent-hub-board')
  const script = `#!/bin/sh\n# Generated by Agent Hub: runs the repository board CLI.\nELECTRON_RUN_AS_NODE=1 exec ${shellQuote(board.runtime)} ${shellQuote(board.cli)} "$@"\n`
  let current = ''
  try { current = readFileSync(path, 'utf8') } catch { /* first write */ }
  if (current !== script) {
    mkdirSync(bin, { recursive: true })
    writeFileSync(`${path}.tmp`, script, { mode: 0o755 })
    renameSync(`${path}.tmp`, path)
  }
  return bin
}

/** Agent CLIs Agent Hub integrates with beyond running them in a PTY. A
 *  custom profile counts when its executable is one of these CLIs. */
export type Provider = 'claude' | 'codex'
export function providerFor(kind: string, executable = ''): Provider | null {
  if (kind === 'claude' || kind === 'codex') return kind
  if (kind !== 'custom') return null
  const name = basename(executable)
  return name === 'claude' || name === 'codex' ? name : null
}

export interface LaunchContext {
  repo: string
  /** Agent Hub Session (context) id, so board tools find the working Task. */
  sessionId: string
  board?: BoardRuntime
  /** Per-terminal event endpoint for hooks; absent disables hooks. */
  hookUrl?: string
  /** A conversation to continue, from an earlier run of this terminal. */
  resumeId?: string
}
export interface LaunchPlan { args: string[]; env: Record<string, string>; conversationId?: string }

/** Hook command: post the event JSON on stdin to this terminal's endpoint.
 *  It never fails the agent's own action, even when Agent Hub is gone. */
export const HOOK_COMMAND = `curl -s -o /dev/null -m 2 -H 'content-type: application/json' --data-binary @- "$AGENT_HUB_HOOK_URL" || true`

const boardServer = (context: LaunchContext) => context.board ? {
  command: context.board.runtime, args: [context.board.cli, 'mcp'],
  env: { ELECTRON_RUN_AS_NODE: '1', AGENT_HUB_REPO: context.repo, AGENT_HUB_SESSION_ID: context.sessionId },
} : null

/** Extra argv and environment for an integrated agent: hooks that report its
 *  state, the board MCP server, and a stable conversation id to resume. The
 *  profile's own arguments come first and are never rewritten. */
export function launchPlan(provider: Provider | null, baseArgs: string[], context: LaunchContext): LaunchPlan {
  const env: Record<string, string> = context.hookUrl ? { AGENT_HUB_HOOK_URL: context.hookUrl } : {}
  if (provider === 'claude') {
    const args = [...baseArgs]
    const server = boardServer(context)
    if (server) args.push('--mcp-config', JSON.stringify({ mcpServers: { 'agent-hub': { type: 'stdio', ...server } } }))
    if (context.hookUrl) {
      const hook = [{ type: 'command', command: HOOK_COMMAND, timeout: 5 }]
      const all = [{ matcher: '*', hooks: hook }]
      args.push('--settings', JSON.stringify({ hooks: {
        SessionStart: [{ hooks: hook }], UserPromptSubmit: [{ hooks: hook }], PreToolUse: all,
        PermissionRequest: all, Notification: [{ hooks: hook }], Stop: [{ hooks: hook }],
      } }))
    }
    if (context.resumeId) return { args: [...args, '--resume', context.resumeId], env, conversationId: context.resumeId }
    const conversationId = randomUUID()
    return { args: [...args, '--session-id', conversationId], env, conversationId }
  }
  if (provider === 'codex') {
    // Codex takes TOML values through repeatable `-c key=value` overrides,
    // layered over the user's own config for this run only.
    const toml = (value: string) => JSON.stringify(value)
    const flags: string[] = []
    const set = (key: string, value: string) => flags.push('-c', `${key}=${value}`)
    const server = boardServer(context)
    if (server) {
      set('mcp_servers.agent_hub.command', toml(server.command))
      set('mcp_servers.agent_hub.args', `[${server.args.map(toml).join(',')}]`)
      set('mcp_servers.agent_hub.env', `{${Object.entries(server.env).map(([key, value]) => `${key}=${toml(value)}`).join(',')}}`)
    }
    if (context.hookUrl) {
      // `notify` runs once per finished turn with the event JSON appended as
      // the last argument, which curl posts as the request body.
      set('notify', `[${['curl', '-s', '-o', '/dev/null', '-m', '2', '-H', 'content-type: application/json', context.hookUrl, '--data-raw'].map(toml).join(',')}]`)
      // Approvals and questions arrive as OSC 9 escapes on the screen.
      set('tui.notifications', '["approval-requested","plan-mode-prompt","async-question"]')
      set('tui.notification_method', '"osc9"')
      set('tui.notification_condition', '"always"')
    }
    const resume = context.resumeId ? ['resume', context.resumeId] : []
    return { args: [...resume, ...baseArgs, ...flags], env, conversationId: context.resumeId }
  }
  return { args: baseArgs, env }
}
